import {Transaction} from "../types/Transaction";




export const transactions: Transaction[] = [
    {"TransactionId": "101", "Status": "Pending", "Type": "Withdrawal", "ClientName": "Dale Cotton", "Amount": "$28.43"},
    {"TransactionId": "102", "Status": "Completed", "Type": "Refill", "ClientName": "Paul Carter", "Amount": "$45.16"},
    {"TransactionId": "103", "Status": "Cancelled", "Type": "Refill", "ClientName": "Caldwell Reid", "Amount": "$63.00"},
    {"TransactionId": "104", "Status": "Cancelled", "Type": "Refill", "ClientName": "Quentin Bonner", "Amount": "$64.52"},
    {"TransactionId": "105", "Status": "Cancelled", "Type": "Withdrawal", "ClientName": "Colt Joyce", "Amount": "$70.67"},
    {"TransactionId": "106", "Status": "Completed", "Type": "Refill", "ClientName": "Neil Walls", "Amount": "$99.36"},
    {"TransactionId": "107", "Status": "Completed", "Type": "Refill", "ClientName": "Slade Rios", "Amount": "$52.60"},
    {"TransactionId": "108", "Status": "Cancelled", "Type": "Withdrawal", "ClientName": "Graham Harrell", "Amount": "$47.51"},
    {"TransactionId": "109", "Status": "Completed", "Type": "Withdrawal", "ClientName": "Kirk Byers", "Amount": "$96.35"},
    {"TransactionId": "110", "Status": "Cancelled", "Type": "Withdrawal", "ClientName": "Holmes Howell", "Amount": "$93.81"},
    {"TransactionId": "111", "Status": "Cancelled", "Type": "Refill", "ClientName": "Flynn Whitley", "Amount": "$95.75"},
    {"TransactionId": "112", "Status": "Cancelled", "Type": "Refill", "ClientName": "Chase Salas", "Amount": "$95.25"},
    {"TransactionId": "113", "Status": "Completed", "Type": "Withdrawal", "ClientName": "Aquila Skinner", "Amount": "$69.47"},
    {"TransactionId": "114", "Status": "Completed", "Type": "Refill", "ClientName": "Len Snyder", "Amount": "$78.59"},
    {"TransactionId": "115", "Status": "Completed", "Type": "Refill", "ClientName": "Thaddeus Watts", "Amount": "$38.72"},
    {"TransactionId": "116", "Status": "Pending", "Type": "Withdrawal", "ClientName": "Nehru Franks", "Amount": "$51.22"},
    {"TransactionId": "117", "Status": "Completed", "Type": "Withdrawal", "ClientName": "Lester Oconnor", "Amount": "$13.45"},
    {"TransactionId": "118", "Status": "Pending", "Type": "Refill", "ClientName": "Jameson White", "Amount": "$38.76"},
    {"TransactionId": "119", "Status": "Completed", "Type": "Refill", "ClientName": "Christian Stanton", "Amount": "$91.79"},
    {"TransactionId": "120", "Status": "Pending", "Type": "Withdrawal", "ClientName": "Vance Lowery", "Amount": "$13.40"},
    {"TransactionId": "121", "Status": "Cancelled", "Type": "Refill", "ClientName": "Kevin Wiley", "Amount": "$42.04"},
    {"TransactionId": "122", "Status": "Pending", "Type": "Withdrawal", "ClientName": "Plato Clay", "Amount": "$51.64"},
    {"TransactionId": "123", "Status": "Pending", "Type": "Refill", "ClientName": "Salvador Hardy", "Amount": "$60.54"},
    {"TransactionId": "124", "Status": "Pending", "Type": "Withdrawal", "ClientName": "Owen Langley", "Amount": "$64.23"},
    {"TransactionId": "125", "Status": "Completed", "Type": "Refill", "ClientName": "Zeus Ferrell", "Amount": "$32.59"},
    {"TransactionId": "126", "Status": "Completed", "Type": "Refill", "ClientName": "Hayden Puckett", "Amount": "$14.49"},
    {"TransactionId": "127", "Status": "Completed", "Type": "Refill", "ClientName": "Raja Fitzpatrick", "Amount": "$56.88"},
    {"TransactionId": "128", "Status": "Completed", "Type": "Withdrawal", "ClientName": "Hedley Mccall", "Amount": "$33.87"},
    {"TransactionId": "129", "Status": "Pending", "Type": "Withdrawal", "ClientName": "Ivan Noble", "Amount": "$55.21"},
    {"TransactionId": "130", "Status": "Completed", "Type": "Withdrawal", "ClientName": "Steven Soto", "Amount": "$94.57"},
    {"TransactionId": "131", "Status": "Pending", "Type": "Refill", "ClientName": "Omar Hutchinson", "Amount": "$54.11"},
    {"TransactionId": "132", "Status": "Completed", "Type": "Withdrawal", "ClientName": "Thor Mack", "Amount": "$7.84"},
    {"TransactionId": "133", "Status": "Pending", "Type": "Withdrawal", "ClientName": "Charles Sullivan", "Amount": "$76.74"},
    {"TransactionId": "134", "Status": "Pending", "Type": "Withdrawal", "ClientName": "Thor Gilbert", "Amount": "$90.68"},
    {"TransactionId": "135", "Status": "Completed", "Type": "Withdrawal", "ClientName": "Gabriel Fox", "Amount": "$54.20"},
    {"TransactionId": "136", "Status": "Cancelled", "Type": "Withdrawal", "ClientName": "Driscoll Tate", "Amount": "$72.10"},
    {"TransactionId": "137", "Status": "Completed", "Type": "Refill", "ClientName": "Armando Chase", "Amount": "$99.65"},
    {"TransactionId": "138", "Status": "Cancelled", "Type": "Withdrawal", "ClientName": "Thane Donovan", "Amount": "$84.18"},
    {"TransactionId": "139", "Status": "Completed", "Type": "Refill", "ClientName": "Price Dudley", "Amount":    "$15.81"},
    {"TransactionId": "140", "Status": "Cancelled", "Type": "Withdrawal", "ClientName": "Yuli Brown", "Amount": "$67.19"},
    {"TransactionId": "141", "Status": "Cancelled", "Type": "Refill", "ClientName": "Jin Prince", "Amount": "$95.10"},
    {"TransactionId": "142", "Status": "Pending", "Type": "Refill", "ClientName": "Beck Butler", "Amount": "$64.97"},
    {"TransactionId": "143", "Status": "Pending", "Type": "Withdrawal", "ClientName": "Victor Quinn", "Amount": "$16.88"},
    {"TransactionId": "144", "Status": "Cancelled", "Type": "Withdrawal", "ClientName": "Dane Barker", "Amount": "$25.31"},
    {"TransactionId": "145", "Status": "Cancelled", "Type": "Withdrawal", "ClientName": "Felix Harper", "Amount": "$82.36"},
    {"TransactionId": "146", "Status": "Pending", "Type": "Refill", "ClientName": "Merrill Mullen", "Amount": "$30.56"},
    {"TransactionId": "147", "Status": "Cancelled", "Type": "Refill", "ClientName": "Laith Villarreal", "Amount": "$74.68"},
    {"TransactionId": "148", "Status": "Completed", "Type": "Refill", "ClientName": "Abraham Justice", "Amount": "$63.24"},
    {"TransactionId": "149", "Status": "Completed", "Type": "Refill", "ClientName": "Nathan Whitfield", "Amount": "$59.82"},
    {"TransactionId": "150", "Status": "Completed", "Type": "Refill", "ClientName": "David Rice", "Amount": "$84.71"},
    {"TransactionId": "151", "Status": "Completed", "Type": "Withdrawal", "ClientName": "Reuben Webb", "Amount": "$87.83"},
    {"TransactionId": "152", "Status": "Completed", "Type": "Withdrawal", "ClientName": "Lawrence Duffy", "Amount": "$10.96"},
    {"TransactionId": "153", "Status": "Pending", "Type": "Refill", "ClientName": "Hakeem Acevedo", "Amount": "$40.66"},
    {"TransactionId": "154", "Status": "Pending", "Type": "Refill", "ClientName": "Daquan Shields", "Amount": "$16.36"},
    {"TransactionId": "155", "Status": "Completed", "Type": "Refill", "ClientName": "Adam Shepherd", "Amount": "$45.97"},
    {"TransactionId": "156", "Status": "Pending", "Type": "Refill", "ClientName": "Derek Todd", "Amount": "$52.88"},
    {"TransactionId": "157", "Status": "Cancelled", "Type": "Withdrawal", "ClientName": "Nigel Roach", "Amount": "$46.92"},
    {"TransactionId": "158", "Status": "Pending", "Type": "Refill", "ClientName": "Oleg Willis", "Amount": "$97.76"},
    {"TransactionId": "159", "Status": "Pending", "Type": "Withdrawal", "ClientName": "Chancellor Stewart", "Amount": "$70.30"},
    {"TransactionId": "160", "Status": "Pending", "Type": "Withdrawal", "ClientName": "Gray Barry", "Amount": "$85.78"},
    {"TransactionId": "161", "Status": "Cancelled", "Type": "Withdrawal", "ClientName": "Cairo Mack", "Amount": "$73.98"},
    {"TransactionId": "162", "Status": "Pending", "Type": "Refill", "ClientName": "Erasmus Oneal", "Amount": "$89.31"},
    {"TransactionId": "163", "Status": "Pending", "Type": "Refill", "ClientName": "Levi Shepherd", "Amount": "$64.08"},
    {"TransactionId": "164", "Status": "Cancelled", "Type": "Withdrawal", "ClientName": "Cody York", "Amount": "$70.00"},
    {"TransactionId": "165", "Status": "Cancelled", "Type": "Refill", "ClientName": "Armand Miller", "Amount": "$10.93"},
    {"TransactionId": "166", "Status": "Completed", "Type": "Withdrawal", "ClientName": "Jameson Warren", "Amount": "$90.01"},
    {"TransactionId": "167", "Status": "Pending", "Type": "Withdrawal", "ClientName": "Merritt Nieves", "Amount": "$19.69"},
    {"TransactionId": "168", "Status": "Completed", "Type": "Withdrawal", "ClientName": "Callum Rosa", "Amount": "$43.04"},
    {"TransactionId": "169", "Status": "Pending", "Type": "Withdrawal", "ClientName": "James Garcia", "Amount": "$92.82"},
    {"TransactionId": "170", "Status": "Pending", "Type": "Withdrawal", "ClientName": "Kasimir Sandoval", "Amount": "$37.16"},
    {"TransactionId": "171", "Status": "Completed", "Type": "Withdrawal", "ClientName": "Noble Frank", "Amount": "$94.88"},
    {"TransactionId": "172", "Status": "Pending", "Type": "Withdrawal", "ClientName": "Cade Emerson", "Amount": "$47.94"},
    {"TransactionId": "173", "Status": "Cancelled", "Type": "Refill", "ClientName": "Sean Head",    "Amount": "$11.36"},
    {"TransactionId": "174", "Status": "Cancelled", "Type": "Withdrawal", "ClientName": "Ross Crawford", "Amount": "$24.13"},
    {"TransactionId": "175", "Status": "Pending", "Type": "Refill", "ClientName": "Salvador Hopkins", "Amount": "$47.86"},
    {"TransactionId": "176", "Status": "Cancelled", "Type": "Withdrawal", "ClientName": "Quamar Peck", "Amount": "$5.46"},
    {"TransactionId": "177", "Status": "Cancelled", "Type": "Withdrawal", "ClientName": "Norman Whitley", "Amount": "$35.88"},
    {"TransactionId": "178", "Status": "Completed", "Type": "Withdrawal", "ClientName": "Dexter Chandler", "Amount": "$34.61"},
    {"TransactionId": "179", "Status": "Completed", "Type": "Withdrawal", "ClientName": "Adam Curry", "Amount": "$69.92"},
    {"TransactionId": "180", "Status": "Completed", "Type": "Withdrawal", "ClientName": "Elmo Huffman", "Amount": "$15.07"},
    {"TransactionId": "181", "Status": "Cancelled", "Type": "Withdrawal", "ClientName": "Eaton Sanchez", "Amount": "$31.20"},
    {"TransactionId": "182", "Status": "Completed", "Type": "Refill", "ClientName": "Cooper Cantrell", "Amount": "$14.69"},
    {"TransactionId": "183", "Status": "Cancelled", "Type": "Withdrawal", "ClientName": "Kermit Lawrence", "Amount": "$86.51"},
    {"TransactionId": "184", "Status": "Pending", "Type": "Refill", "ClientName": "Arsenio Wilkinson", "Amount": "$76.06"},
    {"TransactionId": "185", "Status": "Completed", "Type": "Refill", "ClientName": "Francis Marks", "Amount": "$93.64"},
    {"TransactionId": "186", "Status": "Completed", "Type": "Withdrawal", "ClientName": "Robert Nunez", "Amount": "$62.78"},
    {"TransactionId": "187", "Status": "Pending", "Type": "Refill", "ClientName": "Hyatt Spence", "Amount": "$74.23"},
    {"TransactionId": "188", "Status": "Pending", "Type": "Withdrawal", "ClientName": "Elmo Oliver", "Amount": "$0.73"},
    {"TransactionId": "189", "Status": "Cancelled", "Type": "Refill", "ClientName": "Brent Skinner", "Amount": "$48.10"},
    {"TransactionId": "190", "Status": "Pending", "Type": "Refill", "ClientName": "Linus Garcia", "Amount": "$61.99"},
    {"TransactionId": "191", "Status": "Pending", "Type": "Refill", "ClientName": "Bruce Vaughn", "Amount": "$16.55"},
    {"TransactionId": "192", "Status": "Cancelled", "Type": "Refill", "ClientName": "Galvin Knapp", "Amount": "$90.98"},
    {"TransactionId": "193", "Status": "Completed", "Type": "Refill", "ClientName": "Timothy Martinez", "Amount": "$36.48"},
    {"TransactionId": "194", "Status": "Cancelled", "Type": "Refill", "ClientName": "Myles Wright", "Amount": "$87.57"},
    {"TransactionId": "195", "Status": "Completed", "Type": "Withdrawal", "ClientName": "Robert Beard", "Amount": "$35.86"},
    {"TransactionId": "196", "Status": "Completed", "Type": "Refill", "ClientName": "Brendan Santana", "Amount": "$38.22"},
    {"TransactionId": "197", "Status": "Cancelled", "Type": "Refill", "ClientName": "Quamar Avery", "Amount": "$34.22"},
    {"TransactionId": "198", "Status": "Completed", "Type": "Withdrawal", "ClientName": "Upton Perez", "Amount": "$32.31"},
    {"TransactionId": "199", "Status": "Completed", "Type": "Withdrawal", "ClientName": "Grady Gordon", "Amount": "$7.33"},
    {"TransactionId": "200", "Status": "Pending", "Type": "Withdrawal", "ClientName": "Mark Velazquez", "Amount": "$66.59"}
];




